### PR TITLE
RFC: V3: Oxc resolver

### PR DESCRIPTION
**Pull request by alshdavid**
Maintaining our own Nodejs resolver is quite difficult, error prone and increases the maintenance/testing surface of Atlapack. This RFC is about replacing our native resolver with an oxc based resolver and supplies a reference for testing.

Using our benchmarks, oxc is 10% faster (though the actual plugin is doing less so YMMV), would like to test this against JFE to see if it resolves the tsconfig issues we are seeing

To use this just add `@atlaspack/resolver-oxc` to the `.parcelrc` file

### CODE REVIEW

**Comment by devongovett** [comment]
FYI, I made Parcel's resolver a lot faster recently (basically rewrote the whole cache): https://github.com/parcel-bundler/parcel/pull/9984

Benchmarked a bunch of resolver crates including OXC: https://github.com/parcel-bundler/parcel/blob/v2/crates/parcel-resolver/benches/benchmark.rs

With caching:

```
cached/parcel_resolver  time:   [1.8614 µs 1.8661 µs 1.8716 µs]
cached/oxc_resolver     time:   [6.4001 µs 6.4171 µs 6.4362 µs]
cached/rspack_resolver  time:   [6.3623 µs 6.3738 µs 6.3856 µs]
cached/deno             time:   [81.661 µs 82.007 µs 82.467 µs]
```

Without caching (creating a fresh cache on each iteration):

```
uncached/parcel_resolver time:   [109.29 µs 109.70 µs 110.13 µs]
uncached/oxc_resolver    time:   [162.42 µs 163.24 µs 164.28 µs]
uncached/rspack_resolver time:   [165.43 µs 166.10 µs 167.01 µs]
uncached/deno            time:   [157.49 µs 157.66 µs 157.88 µs]
```

Published it on crates.io as well in case you want to use it. https://docs.rs/parcel-resolver/

**Comment by IWANABETHATGUY** [comment]
> FYI, I made Parcel's resolver a lot faster recently (basically rewrote the whole cache): [parcel-bundler/parcel#9984](https://github.com/parcel-bundler/parcel/pull/9984)
> 
> Benchmarked a bunch of resolver crates including OXC: https://github.com/parcel-bundler/parcel/blob/v2/crates/parcel-resolver/benches/benchmark.rs
> 
> With caching:
> 
> ```
> cached/parcel_resolver  time:   [1.8614 µs 1.8661 µs 1.8716 µs]
> cached/oxc_resolver     time:   [6.4001 µs 6.4171 µs 6.4362 µs]
> cached/rspack_resolver  time:   [6.3623 µs 6.3738 µs 6.3856 µs]
> cached/deno             time:   [81.661 µs 82.007 µs 82.467 µs]
> ```
> 
> Without caching (creating a fresh cache on each iteration):
> 
> ```
> uncached/parcel_resolver time:   [109.29 µs 109.70 µs 110.13 µs]
> uncached/oxc_resolver    time:   [162.42 µs 163.24 µs 164.28 µs]
> uncached/rspack_resolver time:   [165.43 µs 166.10 µs 167.01 µs]
> uncached/deno            time:   [157.49 µs 157.66 µs 157.88 µs]
> ```
> 
> Published it on crates.io as well in case you want to use it. https://docs.rs/parcel-resolver/

https://x.com/devongovett/status/1855443732654702725?s=46&t=SqAn_WFH4gORgiw6KZBoMw， wow， glad to see that you could optimize the performance in such a short time.

**Comment by IWANABETHATGUY** [comment]
Here is the data in Ubuntu 22.04, SSD, cpu 5950x
**uncached**
image
**cached**
image

**Comment by yyx990803** [comment]
I ran the benchmark myself and the difference doesn't seem to be this significant:

### M2 Pro Macbook Pro

Uncached
```
uncached/parcel_resolver
                        time:   [41.279 µs 41.466 µs 41.758 µs]
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) low mild
  4 (4.00%) high mild
  3 (3.00%) high severe

uncached/oxc_resolver   time:   [51.383 µs 51.610 µs 51.859 µs]
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe

uncached/rspack_resolver
                        time:   [51.416 µs 51.687 µs 51.992 µs]
Found 14 outliers among 100 measurements (14.00%)
  7 (7.00%) high mild
  7 (7.00%) high severe

uncached/deno           time:   [60.985 µs 61.015 µs 61.050 µs]
Found 15 outliers among 100 measurements (15.00%)
  5 (5.00%) low mild
  5 (5.00%) high mild
  5 (5.00%) high severe
```
  
Cached
```
cached/parcel_resolver  time:   [1.7027 µs 1.7062 µs 1.7105 µs]
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

cached/oxc_resolver     time:   [2.5719 µs 2.5753 µs 2.5803 µs]
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  3 (3.00%) high severe

cached/rspack_resolver  time:   [2.5542 µs 2.5672 µs 2.5908 µs]
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) high mild
  6 (6.00%) high severe

cached/deno             time:   [50.357 µs 50.459 µs 50.591 µs]
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe
```

### Linux Ubuntu 22.04 LTS

- CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
- Memory: 64 GB

resolver-bench1
resolver-bench

**Comment by yamadapc** [comment]
I think it does make sense to maintain a resolver because we would rather have no resolver plugins.

Instead, we'd add the few patches we are currently using on resolver plugins to the main rust code.

- - -

@devongovett we can't use parcel resolver because it depends on `dashmap` which we have now validated was causing segmentation faults on our developers machines. There were hundreds of native crashes every day, which are completely fixed by https://github.com/atlassian-labs/atlaspack/pull/10.

That is, there is some unsoundness in the `dashmap` crate which leads to memory corruption and then crashes under a certain workload, which we started to hit. Developers were unable to start the server and make a few builds without a crash prior to this change.

- - -

Regarding benchmark, while it is good to micro-benchmark, it's better to measure a real workload.

We have an internal benchmark, which replays all imports in our application.

On that benchmark, the current master branch of this repository performs as well as the `parcel` master branch before cache optimisation ; the cache optimisation changes made `parcel` resolution slower by a non-negligible amount (10%+).

Most importantly, the absolute times to resolve all imports in the repository are very low when they are executed concurrently (a few seconds to resolve all the imports with multi-threading).

I think that if resolution is a build time bottle-neck today, it is only because the builds are based on crawling the module tree, and it'll be much more efficient to crawl the directory tree directly to parse and discover imports, then run resolution as a second time.

- - -

Note that despite around 30% slower resolver (at the moment) in the master branch, and previously we had a 3x slower resolver than parcel master https://github.com/atlassian-labs/atlaspack/pull/156, the actual build times for this repository are 2x faster to build jira than what is in mainline parcel due to a few optimisations on packaging/optimisation phases.

There is currently some degradation in perf. of the master branch **resolver**, when running new experimental code for building the asset graph in rust. This might be related to removal of `Cow` on certain resolver parts. I am unconvinced it is a performance bottle-neck, but there are other fixes to it.

**Review by yamadapc — CHANGES_REQUESTED** [review]
Let's talk about this internally.

**Comment by devongovett** [comment]
FWIW, oxc_resolver also uses dashmap. Dashmap v6 was recently released as well. Maybe that fixed some issues you saw.

**Comment by yamadapc** [comment]
I was hoping that was the case too, but I had looked at the diff between those dashmap versions and there did not seem to be significant changes that could fix the crashes.

What we have now (thread local caches) performs really close to the concurrent dashmap but has much less surface area for unsoundness and is easier to understand. 

It'd be nice to review this at some point but we were having serious unreliability issues related to crashes (they were common, and certain engineers would experience crashes on every single run of certain builds).

**Comment by alshdavid** [comment]
Will continue this discussion after I get back

**Pull request closed without merging**
